---
- name: Ansible 3 - Storage Management
  hosts: all
  become: true

  tasks:

    - name: Create a new partition with a size of 1GiB
      community.general.parted:
        device: /dev/nvme1n1
        number: 1
        state: present
        fs_type: xfs4
        part_end: 1GiB

    - name: Mount nvme1n1p1 to /automount
      ansible.posix.mount:
        path: /extdrive
        src: /dev/nvme1n1p1
        opts: defaults
        fstype: auto
        state: mounted
